terraform:
  production:
    credentials: "./auth/serviceaccount.json"
    project: "inazrabuu-kube10"
    regions: "asia-southeast1"
    cluster_name: "production-cluster"
    network: "default"
    initial_node_count: 1
    node_count: 3
    node_name: "my-node-pool"
    preemptible: "false"
    machine_type: "n1-standard-1"
    bucket: "terraform-production-a92f4741bc30659f7fd2da8359945e5f"
  testing:
    credentials: "./auth/serviceaccount.json"
    project: "inazrabuu-kube10"
    regions: "asia-southeast1"
    cluster_name: "testing-cluster"
    network: "default"
    initial_node_count: 1
    node_count: 2
    node_name: "my-node-pool"
    preemptible: "true"
    machine_type: "f1-micro"
    bucket: "terraform-testing-c8780c3621cd6eaad9b4e35ef874177d"
